export default ACTION_TYPES = {

  LOGIN: 'LOGIN', 
  USER_TYPE: 'USER_TYPE', 
  LOGOUT:"LOGOUT",
  REMEMBER:"REMEMBER",
  INFO:"INFO",
  FAVOURITES:"FAVOURITES",
  CURRENT_LOCATION:"CURRENT_LOCATION"


};

